### ISSUE TITLE
RecursiveField support

### ISSUE THREAD

**Issue by rsichny** [axnsan12/drf-yasg#109]
We use https://github.com/heywbj/django-rest-framework-recursive library in few of our serializers and we had to create a custom inspector for it. The issue is that i had to copy-paste the code for getting serializer's ref_name. It would be great if the library was refactored to provide that method. Also, there's a small issue with ReferenceResolver which i had to hack.

I can create a PR, the question is if you want to support RecursiveField out of the box, or just refactor the code to provide utility function for getting serializer's ref name?

Somewhat dirty implementation example just to show the copy-paste issue and ReferenceResolver hack: https://gist.github.com/rsichny/eea1b034bdca4e798c3939bf589a03d9

**Comment by axnsan12** [comment]
Both additions would be welcome 😄 

An integration with ``django-rest-framework-recursive``  similar to [the one with ``djangorestframework-camel-case``](https://github.com/axnsan12/drf-yasg/blob/master/src/drf_yasg/inspectors/field.py#L493) would do no harm.

Refactoring the ref_name logic into a method would also make that integration cleaner and help maintenance down the road, so great!

Regarding your code:

```python
            definitions = ReferenceResolver(openapi.SCHEMA_DEFINITIONS).with_scope(openapi.SCHEMA_DEFINITIONS)
            definitions.set(ref_name, openapi.Schema(type=openapi.TYPE_OBJECT))

            return openapi.SchemaRef(definitions, ref_name)
```

I assume this is the hack you were talking about, which you had to do because of [this assert](https://github.com/axnsan12/drf-yasg/blob/d2dc09cb3c765938af32e3c0dcda2e2b31140721/src/drf_yasg/openapi.py#L481), since the serializer you're trying to reference doesn't exist yet.

I think just removing that assertion would be ok, since there may be other cases where one would want a 'forward' reference to a type. Wrong references should be caught by validators at the end anyways, so error checking would not be affected too much.
