### ISSUE TITLE
Allow request body on DELETE

### ISSUE THREAD

**Issue by Amoki** [axnsan12/drf-yasg#118]
According to https://tools.ietf.org/html/rfc7231#section-4.3.5

> A payload within a DELETE request message has no defined semantics;
   sending a payload body on a DELETE request might cause some existing
   implementations to reject the request.

There is no reason to avoid a body in DELETE requests

```python
@method_decorator(name='destroy', decorator=swagger_auto_schema(
    request_body='list of ids',
    responses={status.HTTP_204_NO_CONTENT: 'No content'}
))
>>> drf_yasg.errors.SwaggerGenerationError: request_body can only be applied to (PUT,PATCH,POST)
```

I tried to submit a pull request updating 
```python
class ViewInspector(BaseInspector):
    body_methods = ('PUT', 'PATCH', 'POST', 'DELETE')  #: methods that are allowed to have a request body
```
but many tests fail and I would need help with that.

Thanks for this really good lib :)

**Comment by axnsan12** [comment]
Ok, seems legit; you can open the pull request and we'll see with the errors 😄 

I'm guessing that the tests fail because the code [assumes all methods in ``body_methods`` implicitly have the view's serializer as request body](https://github.com/axnsan12/drf-yasg/blob/master/src/drf_yasg/inspectors/view.py#L104).

I would say this could be solved by adding an ``implicit_body_methods`` array next to the existing one, and switching that ``else`` check to use it. The new array would only have the current three methods, while ``DELETE`` would be added to the existing ``body_methods`` - to not generate a body by default (``GenericView``/``ViewSet`` behavior), while still allowing a request body to be used as a manual override.

**Comment by rsichny** [comment]
this broke the compatibility, now all delete operations have *required* body. IMO body for delete operations should be available for turning on optionally but off by default.

**Comment by axnsan12** [comment]
> So there's no issue other than change of public variable contents

yeah, sorry about that, should have mentioned that part of the old ``body_methods`` functionality was now split into ``implicit_body_methods`` 😅

**Comment by baipaiha** [comment]
Old issue but seeing this exact same text about payload for GET request:
https://tools.ietf.org/html/rfc7231#section-4.3.1
