### ISSUE TITLE
Generate a schema_views per version

### ISSUE THREAD

**Issue by Amoki** [axnsan12/drf-yasg#126]
Is there a way to limit a schema_view to a version ? In order to generate a v1.json and a v2.json.
Using patterns in get_schema_view() seems really complicated for this use case.

If there is currently no way to do that, I'm able to spent some time in the implementation :D

**Comment by Amoki** [comment]
This is exactly what I want!
I'm using NamespaceVersioning so it's totally implicit (when REST Framework is correctly configured...).
Dunno why, but I thought I had something to do... This lib is really awesome :D

**Comment by neilfrndes** [comment]
I tried implementing different schemas for different versions. However, I was unsuccessful. After investigating drf_yasg code for a couple of hours, it looks like this particular snippet is the problem.

https://github.com/axnsan12/drf-yasg/blob/ab6444a32e222a4b9df12620fc484814c165f701/src/drf_yasg/generators.py#L52-L54

the should_include_endpoint function always returns false because the namespace argument is None all the time.
