### ISSUE TITLE
Doubt: There is a way of putting more than one request example's JSON

### ISSUE THREAD

**Issue by Gabriel-Arimatea** [axnsan12/drf-yasg#145]
Hello, sorry if there is any English grammar errors. 

I have a little doubt: searching the Redoc itself, in their live demo, method 'Add a new pet to the store' (http://rebilly.github.io/ReDoc/#operation/addPet) on the 'Request Samples' > Payload, there is options 'cat', 'dog' and 'bee', showing different JSON each one. I'm wondering if there is a way to do that (more than one serializer per method showing other possibilities) or if there is plans to doing so in near future?

Thanks

**Comment by axnsan12** [comment]
That is not "more than one request example". That is discriminator-based polymorphism. You can achieve this with drf-yasg (you can achieve ANY swagger document), but since there is no clear standard for serializer polymorphism you'll have to settle on something and implement the schema generation manually.

See https://github.com/axnsan12/drf-yasg/issues/100
