### ISSUE TITLE
Incorrectly renders CamelCase in all views

### ISSUE THREAD

**Issue by glujan** [axnsan12/drf-yasg#156]
In my app I'm using [djangorestframework-camel-case](https://github.com/vbabiy/djangorestframework-camel-case) only for some subset of views by setting their parser and renderer classes to `CamelCaseJSONParser` and `CamelCaseJSONRenderer` respectively. My default parser and renderer classes are set to `JSONParser` and `JSONRenderer` in my project settings.

It looks like using camelCase for just one view is causing `drf-yasg` to use camelCase in all views.

**Comment by axnsan12** [comment]
As you can see form the [demo project](https://drf-yasg-demo.herokuapp.com/cached/redoc/#tag/snippets), this is not generally the case. Only views with the parser and renderer you mentioned are converted. Thus it must be something more particular to your project, so please provide some details.

You should note however that due to the nature of OpenAPI and the current implementation of ``drf-yasg``, if you use the same serializer in multiple views, where only some of them are ``camelCase``d, the Swagger model associated with that serializer will be ``camelCase``d everywhere. See also the note [here](https://drf-yasg.readthedocs.io/en/stable/custom_spec.html#inspector-classes). You can work around this by not using named Swagger models ([setting ``ref_name`` to ``None`` on the serializer](https://drf-yasg.readthedocs.io/en/stable/custom_spec.html?highlight=ref_name#serializer-meta-nested-class)).

**Comment by glujan** [comment]
Thank you for detailed response.

I'm indeed reusing some serializers and your note about `ref_name` was what I was missing - setting it to `None` or to string to not clash with original serializer solves the issue.

**Comment by glujan** [comment]
Note: this also happens if I'm not reusing serializers but there is a name clash in across different Django applications. Setting different `ref_name` helps with those issues as well.

Maybe `drf-yasg` should show a warning about that.

**Comment by axnsan12** [comment]
> Maybe drf-yasg should show a warning about that or at least allow to prefix model name with app name.

Yeah, both of those seem reasonable.
