### ISSUE TITLE
Suggestion: move SWAGGER_DEFAULTS so it can be imported into user's settings.py?

### ISSUE THREAD

**Issue by therefromhere** [axnsan12/drf-yasg#182]
Would it be a good idea to have `SWAGGER_DEFAULTS` in a module that doesn't import django.conf.settings so that a user could import it into their settings.py?

The main use case for this would be so they can add custom inspectors to the default ones automatically.

eg:

```
from drf_yasg import default_settings

SWAGGER_SETTINGS = {
    "DEFAULT_FIELD_INSPECTORS": ["myproject.contrib.inspectors.MyInspector"] + default_settings["SWAGGER_DEFAULTS"]["DEFAULT_FIELD_INSPECTORS"]
}
```

Potential problems with this:

* Order of this list matters so maybe would cause problems (eg if people append to the list instead of adding to the start it'll be ignored)
* Also import into settings.py is a code smell
* A couple of the existing settings (`LOGIN_URL`, `LOGOUT_URL`) depend on django.conf.settings so would need special handling

**Comment by axnsan12** [comment]
I don't know if this is something we'd want to enable.

I kind of prefer forcing users to take ownership of their ``DEFAULT_FIELD_INSPECTORS`` since, as you said, order matters and having additional inspectors unexpectedly pop up might break things. This is in line with Django's and DRF's approach to similar settings (middleware, auth/permission/paginator classes etc).

The ``django.conf.settings`` problem is a non-issue since it could be avoided by using sentry values.

**Comment by therefromhere** [comment]
No worries, just a thought.  I'll close.
