### ISSUE TITLE
Adding  application/x-www-form-urlencoded to select list application/json in content type - try out

### ISSUE THREAD

**Issue by GmAccount** [axnsan12/drf-yasg#218]
Hi Team,
my view accept now the content type :  application/x-www-form-urlencoded  
after adding the decorator : @parser_classes((JSONParser,FormParser,MultiPartParser))

please, how can i try-out with the new content type ( doesn't appear in try out modal ) ?

Thanks

**Comment by axnsan12** [comment]
Unfortunately this is a limitation/quirk of OpenAPI v2 and the way I chose to work around it - a view's body can either be form-encoded with a form editor (as a set of Parameters) or passed as a raw body with a specified encoding (as a Schema object). 

The two options are incompatible at the OpenAPI specification level and thus this library chooses to differentaite between them by a simple rule of thumb - it is a form request if ALL accepted encodings are form types (multipart or urlencoded), otherwise it's a raw request.

I'm open to any ideas/suggestions about how this could be handled according to current limitations.
