### ISSUE TITLE
JSONField support

### ISSUE THREAD

**Issue by mhamzawey** [axnsan12/drf-yasg#246]
How can I override the JSON field in the examples section?

**Comment by markddavidoff** [comment]
@mhamzawey I think you'll need to clarify what you mean.

**Comment by mhamzawey** [comment]
The `JsonField` in the Serializer is not reflected in the swagger documentation.  But I found out that if we changed the `JsonField` in the serializer to `DictField` it will work perfectly.

**Comment by axnsan12** [comment]
This is tricky because ``JSONField`` can technically represent more than objects/dicts (i.e. arrays, numbers, booleans, strings, etc.). So assuming it's equivalent to ``DictField`` won't work for the general case, since in fact it can be *anything* (which OpenAPI can't even express, a specific type is required for all fields)

**Comment by axnsan12** [comment]
I'm closing this since it has no real solution. #245 should some day provide a way to override the field on a case by case basis.
