### ISSUE TITLE
openapi.FORMAT_EMAIL not working

### ISSUE THREAD

**Issue by zzinny** [axnsan12/drf-yasg#413]
Even though I specified `format=openapi.FORMAT_EMAIL` for a `Parameter`, when I try sending a test request in swagger UI with an invalid email values like "123" or anything that does not contain `@`, that values were passed. I think the `FORMAT_EMAIL` specification does not check email validity.

What's the role of `format=openapi.FORMAT_EMAIL`?

Does it has any special role as the format `format=openapi.FORMAT_PASSWORD` hides password in html textfield?

**Comment by etene** [comment]
Hello,

`FORMAT_EMAIL` is actually [not defined in the Swagger spec](https://swagger.io/docs/specification/data-models/data-types/), but in JSON-Schema, [according to the source code](https://github.com/axnsan12/drf-yasg/blob/master/src/drf_yasg/openapi.py#L41).

Anyway, what is checked/displayed depends exclusively on your client. `drf-yasg` generates the spec, but doesn't handle this kind of validation.

Since Swagger UI is based on the Swagger spec, I'm not surprised it doesn't handle types that aren't in it.

**Comment by axnsan12** [comment]
@etene is correct here. `format` has no meaning beyond what the OpenAPI client gives it.
