### ISSUE TITLE
Unknown error when try to use serializers with the same name

### ISSUE THREAD

**Issue by p4m-dev** [axnsan12/drf-yasg#455]
![Screenshot from 2019-09-15 16-54-15](https://user-images.githubusercontent.com/31926941/64922687-abff7a00-d7da-11e9-87df-c0f144d77c62.png)

Library raises unknown error when i try to open swagger or redoc page. All I have in logs is:
`
Internal Server Error: /redoc/
`
When serializers have diferent names all works fine.

**Comment by etene** [comment]
Hello,

Since the resulting swagger `Schema`s are named after their serializer class, you're not supposed to have two serializers with the same name, or they will clash. This could explain your problem.

You could try setting a different `ref_name` on the identical serializer's `Meta`, that should probably fix your issue. See https://drf-yasg.readthedocs.io/en/stable/custom_spec.html#serializer-meta-nested-class.

Although I would recommend renaming your serializers instead.
