### ISSUE TITLE
Not showing post parameters for ObtainAuthToken view

### ISSUE THREAD

**Issue by AlexByte** [axnsan12/drf-yasg#484]
ObtainAuthToken https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication
`    url(r'^api-token-auth/', CustomAuthToken.as_view())`

Why django-rest-swagger is showing them by default?
i did this way https://drf-yasg.readthedocs.io/en/stable/custom_spec.html#the-swagger-auto-schema-decorator
```
decorated_auth_view = swagger_auto_schema(
    method='post',
    request_body=AuthTokenSerializer
)(obtain_auth_token)


urlpatterns = [
   ...
   url(r'^login/$', decorated_auth_view)
]
```

**Comment by captain-fox** [comment]
I have the same issue. Though @AlexByte `decorated_auth_view` solution does work it still seems like overkill. Is the reason for lack of automatic generation of schema because drf-yasg does not support `APIViews`?

**Comment by AlexByte** [comment]
My solution may lead to random bugs in re-declaring parameters.

**Comment by axnsan12** [comment]
The solution in the post is the correct way to handle this and is not in any way overkill.

You are correct, there is no way to automatically support plain APIView since they do not have a convention declare the serializer class used.

django-rest-swagger shows the schema because the view provides a manual coreschema override, which will likely stop working in later versions of DRF.
