### ISSUE TITLE
Rendering of DateTime Range Filter

### ISSUE THREAD

**Issue by mrname** [axnsan12/drf-yasg#506]
I am using drf-yasg in conjunction with django-filter, and have a filter as follows:

```
created = filters.IsoDateTimeFromToRangeFilter(field_name='created_at')
```

This in turn allows for the query parameters `created_before` and `created_after`. However, drf-yasg adds `created` as a query parameter, and ignores the `_before` and `_after`. I'm guessing this relates more to the way that django-filter exposes (or does not expose) the filter field.

I manually added the `_before` and `_after` parameters and that works well, but since there is no way to get ride of the auto-generated `created` param in the swagger, it is a bit confusing for clients. 

Happy to dig into the code to work up a PR (either in this repo or django-filter), but wanted to check to make sure I am not missing something or doing something wrong.

**Comment by dmartin** [comment]
Noting a similar thing with a `RangeFilter` - I only get `fieldname` automatically as a query parameter (which doesn't do anything by itself) instead of `fieldname_min` and `fieldname_max`.
I'll manually create the schema in my case for now.

**Comment by dmartin** [comment]
Looking into this a little more I believe the issue lies with `django-filter` rather than this project. `django-filter` generates schemas [here](https://github.com/carltongibson/django-filter/blob/c98e52d80d8deb626fe5f4826cf2872e79a86459/django_filters/rest_framework/backends.py) (`get_schema_fields`) and just naïvely creates a Field with each filter's name. You can override this method and customize the generated fields based on the filter type.

**Comment by axnsan12** [comment]
Yep, seems to be a django-filter issue. I don't think there's much we can do on our side.
