### ISSUE TITLE
cache_timeout parameter not working

### ISSUE THREAD

**Issue by glassresistor** [axnsan12/drf-yasg#513]
I tried using cache_timeout but it neither worked in production or local dev.

Here is the diff that fixed it.  It might be best just to document how to wrap it with cache_page rather than doing it internally.

```
-    url(r'^api/swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(
-        cache_timeout=3600), name='schema-json'),
-    url(r'^api/swagger/$', schema_view.with_ui('swagger',
-                                               cache_timeout=3600),
+    url(r'^api/swagger(?P<format>\.json|\.yaml)$',
+        cache_page(60 * 60)(schema_view.without_ui()), name='schema-json'),
+    url(r'^api/swagger/$', cache_page(60 * 60)(schema_view.with_ui('swagger')),
```

**Comment by axnsan12** [comment]
How do you mean it didn't work? The cache_timeout parameter is supposed to enable server-side caching, i.e. redis, memcache or in-process memory. 

It explicitly disables browser caching by suppressing Cache-Control response headers, so if that's what you're looking at it will seem to not work. It will also by default vary the cache on the Cookie and Authorization headers, since different users might see different schemas based on permissions.

You can verify that it works even on the demo page - https://drf-yasg-demo.herokuapp.com/cached/swagger.json takes <100ms to refresh, while https://drf-yasg-demo.herokuapp.com/swagger.json takes 500ms+.
