### ISSUE TITLE
cannot import name 'available_attrs' from 'django.utils.decorators' 

### ISSUE THREAD

**Issue by joseph-vedadi** [axnsan12/drf-yasg#650]
File ".pyenv/versions/3.7.3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/urls.py", line 7, in <module>
    from drf_yasg.views import get_schema_view
  File "/.venv/lib/python3.7/site-packages/drf_yasg/views.py", line 5, in <module>
    from django.utils.decorators import available_attrs
ImportError: cannot import name 'available_attrs' from 'django.utils.decorators' (/.venv/lib/python3.7/site-packages/django/utils/decorators.py)

**Comment by joseph-vedadi** [comment]
@blueyed @blueyed @nedbat @beaugunderson  Do you know?

**Comment by beaugunderson** [comment]
@joseph-vedadi looks like `available_attrs` was deprecated; you can replace that reference with one to `functools.WRAPPER_ASSIGNMENTS` (or downgrade django to a version before it was removed)

**Comment by joseph-vedadi** [comment]
@beaugunderson Which version is that ?

**Comment by beaugunderson** [comment]
you can figure that out by searching the release notes :)

**Comment by joseph-vedadi** [comment]
@beaugunderson  Thank you :)
When this package will be updated?

**Comment by beaugunderson** [comment]
i'm not sure about that error--i can tell you the versions we are using right now that work:

```
drf-yasg==1.17.1
django==3.0.7
django-rest-framework==3.11.0
```

as for when this will get updated, i can tell you that when my company needs to upgrade to django 3.1+ we'll likely open a PR here to fix the deprecations, but hopefully someone beats us to that :)

**Comment by beaugunderson** [comment]
@joseph-vedadi apologies, this fix is already in this library! so the initial version of `drf-ysag` tried was too old; you should upgrade `drf-yasg` instead of downgrading `django` :)

you can see that `WRAPPER_ASSIGNMENTS` is imported here: https://github.com/axnsan12/drf-yasg/blob/master/src/drf_yasg/views.py#L2

**Comment by joseph-vedadi** [comment]
so what combination you recommend ?
Thank you so much for your help

**Comment by axnsan12** [comment]
Latest version now works for all django>=2.2 drf>=3.10. Closing.

**Comment by eddiequinteros** [comment]
It seems that this issue was either never fixed or it resurfaced again.
Ubuntu 20.04.4 system up to date with latest packages and

# pip list|grep drf
drf-yasg               1.20.0  
# # pip list|grep Django
Django                 3.2 
# pip list|grep django
django-appconf         1.0.3               
django-compressor      2.2                 
django-debreach        2.0.1               
django-pyscss          2.0.2               
django-utils-six       2.0                 
djangorestframework    3.13.1    

running openstack-horizon fails with
ImportError: cannot import name 'available_attrs' from 'django.utils.decorators' (/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py)

Several tracebacks at onc.

Apache log 
[Traceback.txt](https://github.com/axnsan12/drf-yasg/files/8169260/Traceback.txt)
