### ISSUE TITLE
NOTICE: Consider using drf-yasg2 as an active fork of this project

### ISSUE THREAD

**Issue by johnthagen** [axnsan12/drf-yasg#662]
Unfortunately the community has not been able to contact @axnsan12 for many months. During this time, DRF 3.12 has been released, which is no longer compatible with `drf-yasg` (#641), as well as Django 3.1 and Python 3.9.

In order to continue to keep this project from dying, @JoelLefkowitz gratuitously volunteered to champion a new fork, `drf-yasg2`, which has allowed us to merge in some long awaited fixes (#625) as well as make sure everything is tested on the latest Python, Django, and DRF.

We want to thank @axnsan12 for all of his great work on this project and hope this notice helps other users find a working package for their projects.

**Comment by axnsan12** [comment]
Hello there! 

First of all let me say that I'm very sorry for disappearing and abandoning this project. I won't bore you with excuses but suffice to say that I'm no longer an active user of drf-yasg, DRF, Django, or web development as a whole.

As such I won't have motivation for developing this project any further. 

I've just now been reading over the open issues and PRs I'm very happy to see that other people have taken up the intiative of forking and publishing an updated verison.

As for the fate of this repo, I'm going to do what needs to be done to get it running on the latest Django/drf, so that people who are still using the original package can have a functional version. I'm open to adding you @johnthagen  or @JoelLefkowitz, or anyone else interested, as maintainers to keep this alive.

**Comment by JoelLefkowitz** [comment]
Hiya Cristi!
Glad to hear from you, sorry to hear you’ve left the wonderful world of web dev. 
Let us help you establish a functional version, we can merge in our fixes from the fork and adjust them if you see fit. 
Please do make us maintainers and we'll keep this repo nice and healthy

**Comment by fasih** [comment]
I would also like to become a maintainer of this repo to keep it nice and healthy.

**Comment by creyD** [comment]
So with the new maintainers, will this become the main version again? This would make this issue pretty much obsolete and we should merge the work done in this fork here and try to migrate it's users back here, right?

**Comment by johnthagen** [comment]
Yes, I would say that when @JoelLefkowitz (given the initiative he's shown, I feel as though he makes the most sense as a second maintainer) is promoted to a maintainer, this issue can be closed and we can begin the work of backporting whatever we need from the fork.

**Comment by johnthagen** [comment]
As `drf-yasg` is back in action, I am closing this issue. 🎉

**Comment by johnthagen** [comment]
@axnsan12 Would you consider giving @JoelLefkowitz permissions to publish to PyPI?  That way in the future another maintainer can publish new releases in your absence. As far as I can tell you are the only maintainer listed for the PyPI package itself: https://pypi.org/project/drf-yasg/

You can see @JoelLefkowitz's user name on PyPI here: https://pypi.org/project/drf-yasg2/

- https://pypi.org/user/joellefkowitz/

**Comment by PaulWay** [comment]
Yay for the 'fork-in-the-heart' revivification process!

**Comment by axnsan12** [comment]
@johnthagen pypi publish is automatic via travis for any tagged commit; I've added PyPI permissions to you @JoelLefkowitz  just as a failsafe

**Comment by JoelLefkowitz** [comment]
> @johnthagen pypi publish is automatic via travis for any tagged commit (see CONTRIBUTING.md); I've added PyPI permissions to you @JoelLefkowitz just as a failsafe

Brilliant thank you!

**Comment by kavdev** [comment]
This is what OSS is all about. Awesome to see!
