### ISSUE TITLE
Add support for Marshmallow Schemas

### ISSUE THREAD

**Issue by luxcem** [axnsan12/drf-yasg#72]
[Marshmallow](https://marshmallow.readthedocs.io/) is a Schema module for django rest framework.
It can be used instead of DRF Serializers but is not supported by **drf-yasg**.

It'd be nice to have it.

**Comment by axnsan12** [comment]
Hello,

Marshmallow is an independent schema library which happens to have an integration with django rest framework. Generating OpenAPI specs from Marshmallow schemas falls out of the scope of a library targeted at Django REST Framework serializers (since, as you said, are replaced by Marshmallow).

You could certainly use the code of ``drf-yasg`` to create a library for generating OpenAPI schemas out of Marshmallow, or you could use existing solutions like https://github.com/marshmallow-code/apispec.

Having said that, this is not a feature for this library, so I'm going to close the issue.
