### ISSUE TITLE
Serializer's ReadOnlyField produces always a string, despite being integer in model

### ISSUE THREAD

**Issue by fazpu** [axnsan12/drf-yasg#97]
Hi,

when specifying `id` field in serializer as ReadOnlyField, the generated swagger file labels it as string.

Would it be possible to make it integer?

Thank you for this amazing project!

**Comment by axnsan12** [comment]
Hello,

If your serializer field corresponds to a model field, you should be specifying it as ``IntegerField(read_only=True)``. ``ReadOnlyField`` is normally used for exposing model attributes or properties, which don't really have an introspectable type, which is why it is not specially handled by ``drf-yasg``.

**Comment by fazpu** [comment]
OK, thanks for the insight
